package.json

* Move to `@stripe` org
* Delete incorrect file includes. (Avoiding `Error: Cannot create a string longer than 0x1fffffe8 characters`)

update name to stripe's org

---

README.md

Add note for joining the beta group

Add note for joining the beta group

---

README.md

Add Android and iOS specific integration steps

update doc for native integration

---

example/android/build.gradle
example/ios/Podfile.lock
example/ios/StripeIdentityReactNativeExample.xcodeproj/project.pbxproj

* Android - Update Android example targetSdk to 32, update gradle tools version to 7.2.1
* iOS - Rerun `pod install`
Update dependencies

update android and iOS dependencies

---

example/android/build.gradle

Stripe Android SDK recent made the change: https://github.com/stripe/stripe-android/pull/5495
Fix example Android app

Bump example app's android compile version

---

example/ios/Podfile.lock
stripe-identity-react-native.podspec

use the latest native iOS

---

android/build.gradle
android/gradle.properties
example/ios/Podfile.lock
ios/StripeIdentityReactNative.swift
package.json
stripe-identity-react-native.podspec

* bump up release version to 0.1.3
* bump up iOS version and update android kotlin version that supports ID/Address
* Update the logic to find the correct viewController for iOS, similar to what payments RN [does](https://github.com/stripe/stripe-react-native/blob/master/ios/StripeSdk.swift#L1184-L1197)

Prepare to release 0.1.3

---

android/build.gradle

Support rn 0.69, using the same version with payments: https://github.com/stripe/stripe-react-native/blob/ee97691aa84a25b01527dd8948bb23cfd0dcfae9/android/build.gradle#L11

update gradle version

---

example/ios/Podfile.lock
stripe-identity-react-native.podspec

bump up to latest ios version, see payments [version](https://github.com/stripe/stripe-react-native/blob/bf159065ad4a7552ac0bf19aac4f1cb47ad48190/stripe-react-native.podspec#L4) for reference

bump up ios version

---

example/package.json
example/src/components/Options.tsx
example/src/screens/HomeScreen.tsx
example/src/types.ts
example/src/utils/api.ts
example/yarn.lock
tsconfig.build.json
tsconfig.json
yarn.lock

Update the test app for ID/Address
| Android  | iOS |
| ![3cf5a207-c8d5-4f28-82f7-b4fd992567f6](https://user-images.githubusercontent.com/79880926/227446286-e9d16a9d-e767-49cb-ab8e-19fe9b622b3e.png)  | ![simulator_screenshot_E1425299-E462-4B56-A847-3A79DAF897B0](https://user-images.githubusercontent.com/79880926/227446190-0c4dc6d3-dde0-4d46-a524-9b830e2ff454.png) |

Update test app

---

android/build.gradle
android/gradle.properties
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Bump up to latest iOS and Android version

Bump up native SDK versions

---

android/gradle.properties

downgrade android to 20.24.0

---

CHANGELOG.md
android/gradle.properties

Upgrade to the latest Android patch `20.24.+`
Also add a CHANGELOG file
Related `stripe-react-native` change: https://github.com/stripe/stripe-react-native/pull/1382

Use latest android patch version

---

android/gradle.properties
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Update Android to 20.25.+ and iOS to 23.8.+
payments PR: https://github.com/stripe/stripe-react-native/pull/1384

Update native libraries

---

example/ios/Podfile.lock

Run `pod update` on example ios app

update example app's Podfile.lock

---

android/gradle.properties
stripe-identity-react-native.podspec

match v0.31.1 of stripe-react-native

Upgrade native libraries

---

android/build.gradle
android/gradle.properties
example/ios/Podfile
example/ios/Podfile.lock
example/package.json
example/yarn.lock
package.json
stripe-identity-react-native.podspec
yarn.lock

* Bump Android and iOS native deps
* Update react-native to 0.69.9 (related change: https://github.com/stripe/stripe-react-native/pull/1534)
* Apply a post post install workaround to build the app with xcode 15

Update Android and iOS native deps

---

android/gradle.properties

bump Android to 20.35.+

---

android/gradle.properties
example/android/build.gradle
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Bump Android to `20.37.+ `
Bump iOS to `~>23.22.0`
Bump android example compileSDK to `34`

Bump native Versions

---

android/gradle.properties
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Android: from `20.37.+` to `20.39.+`
iOS: from `~> 23.22.0` to `~> 23.25.0`

Bump native SDKs

---

example/ios/StripeIdentityReactNativeExample/Info.plist

https://react-native-share.github.io/react-native-share/docs/language-support
This change makes sure underline iOS native SDK picks up the correct translated strings.

support multiple retion in the example app

---

android/gradle.properties

Pick up latest Android for a crash fix

update android to 20.44.0

---

CHANGELOG.md
android/gradle.properties
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Upgrade `stripe-android` to 20.52.0
Upgrade `stripe-ios` to 20.30.0
Sync with upgrades made to `stripe-react-native` made [here](https://github.com/stripe/stripe-react-native/pull/1744)

Chore: upgrade native libraries

---

CHANGELOG.md
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Upgrades native iOS version to `24.1.0`
Keep native iOS up-to-date!

Chore: upgrade native iOS version

---

CHANGELOG.md
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Upgrade native iOS version to `24.4.*`
Keep iOS up-to-date!

Chore: Update native iOS version to 24.4.*

---

example/ios/Podfile.lock
stripe-identity-react-native.podspec

Bumping to match https://github.com/stripe/stripe-react-native/pull/1839
Let me know if I missed anything here!
Following code comments in https://github.com/stripe/stripe-react-native/blob/5cd20aba4d259f522097f4e4059423e88c1a7ea3/stripe-react-native.podspec#L4
N/a

Update iOS Stripe SDK to v24.7.0

---

CHANGELOG.md
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Bumping `stripe_version` to match https://github.com/stripe/stripe-ios/pull/4672
Update CHANGELOG for last few versions, whoops!
https://github.com/stripe/stripe-ios/pull/4672

Update iOS Stripe SDK to v24.8.0

---

CHANGELOG.md
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Bumping stripe_version to match https://github.com/stripe/stripe-ios/pull/4705
https://github.com/stripe/stripe-ios/pull/4705

Update iOS Stripe SDK to v24.9.0

---

CHANGELOG.md
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Bumping stripe_version to match https://github.com/stripe/stripe-ios/pull/4760
https://github.com/stripe/stripe-ios/pull/4760

Version bump ios sdk 24.10.0

---

CHANGELOG.md
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Bumping stripe_version to match https://github.com/stripe/stripe-ios/pull/4778
https://github.com/stripe/stripe-ios/pull/4778

Version bump ios sdk 24.11.0

---

CHANGELOG.md
example/ios/Podfile.lock
stripe-identity-react-native.podspec

Bumping stripe_version to match https://github.com/stripe/stripe-ios/pull/4823
https://github.com/stripe/stripe-ios/pull/4823

Version bump ios sdk 24.12.0

---

CHANGELOG.md
example/ios/Podfile.lock
stripe-identity-react-native.podspec

stripe-ios 24.12.1
new ios version

iOS version bump (Fixes verification may fail due to stale model cache)

---

CHANGELOG.md
example/ios/Podfile.lock
stripe-identity-react-native.podspec

iOS version bump 24.13.0

---

CHANGELOG.md
example/ios/Podfile.lock
stripe-identity-react-native.podspec

iOS version bump 24.13.1

---

example/src/utils/api.ts

Update the URL to stripedemos.com and provide codesandbox link

Update Identity backend URL
